apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantreservation-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: restaurantreservation
    spec:
      containers:
        - name: restaurantreservation-container
          image: yichingllin/restaurantreservation-docker
          ports:
            - containerPort: 8081
  selector:
    matchLabels:
      app: restaurantreservation